### ISSUE TITLE
[Bug]: Typescript types casing does not match the API

### ISSUE THREAD

**Issue by nacho-barbano-vs** [PaddleHQ/paddle-js-wrapper#79]
### What happened?

I'm trying to use the data coming from prices preview and price-list endpoints.
Both seem to have a full casing mismatch, on postman, using the official paddle API, I get 100% snake cased properties on all objects.
Types coming both form @paddle-js and node-sdk are showing camelCase.

### Paddle 1.3.2 price-preview.d.ts
![Screenshot 2024-11-26 at 11 29 08 AM](https://github.com/user-attachments/assets/a56eed3a-f15c-4e33-8af6-ee43e3f49195)

### Latest fork on the postman API
<img width="1034" alt="Screenshot 2024-11-26 at 11 32 45 AM" src="https://github.com/user-attachments/assets/de1e11a0-aa83-4c0e-9e3d-9a7d5cd1e681">

### Steps to reproduce

1. Install paddle JS on a TypeScript project, try using the types
2. Compare with the structure and namings on the endpoint responses

### What did you expect to happen?

Types to match the response.

### How are you integrating?

Next.js + TypeScript + Paddle-js 1.3.2

**Comment by danbillson** [comment]
Hi @nacho-barbano-vs, this is done by choice as it is a common pattern to use camel cased variable names in javascript projects whereas apis will commonly use snake case

As there aren't any actions to be taken I'm going to close this issue, be please feel free to reach out if you need any more assistance

**Comment by vijayasingam-paddle** [comment]
Hi @nacho-barbano-vs, 
This library is mainly built for the client side, so it doesn't make a lot of sense to export types in both the cases. 

Maybe you can use the [types](https://github.com/PaddleHQ/paddle-node-sdk/blob/main/src/types/pricing-preview/pricing-preview-response.ts) from our Node SDK while calling this API from the server side. 

Please let us know if we can help you with anything else. 

Thank you.

**Comment by phil221** [comment]
Conventions are conventions, but they can differ across teams and repositories. Custom types are camel-cased for my team's use case, but for a couple different reasons we respect/don't alter snake cased types from external sources. Thus we'd have to run custom case transform functions for every Paddle entity we consume from the client in order to use the pre-defined types. We can do that, but in that case I'd prefer to create my own custom client types copied from the Node SDK. That seems a bit silly to have to do. Is there a serious impediment to exposing the snake cased types from the client library?

**Comment by vijayasingam-paddle** [comment]
Hi @phil221, 

The problem Nacho was facing earlier was when he couldn't use Paddle.js to interact with our API as he was running it on the server and using node SDK to achieve it was the right solution.

Based on the implementations we have seen so far, no one should need snake-cased types while interacting with our API through paddle.js as the library will keep the data and types in the same format.  We do not expect anyone to convert the case of all the properties or write their types as it is redundant work and no one should be doing it. 

Can you please explain your use case a bit more so that we can understand why you need types in the snake case? 

If there is indeed a gap in implementation, we are more than happy to add types in the snake case format. 

Thank you.

**Comment by phil221** [comment]
> Hi [@phil221](https://github.com/phil221),
> 
> The problem Nacho was facing earlier was when he couldn't use Paddle.js to interact with our API as he was running it on the server and using node SDK to achieve it was the right solution.
> 
> Based on the implementations we have seen so far, no one should need snake-cased types while interacting with our API through paddle.js as the library will keep the data and types in the same format. We do not expect anyone to convert the case of all the properties or write their types as it is redundant work and no one should be doing it.
> 
> Can you please explain your use case a bit more so that we can understand why you need types in the snake case?
> 
> If there is indeed a gap in implementation, we are more than happy to add types in the snake case format.
> 
> Thank you.

Hi @vijayasingam-paddle , thanks for your reply. I realized I did leave out some vital information in my comment. I am actually not using Paddle.js currently - our frontend is interacting with the Paddle API through a proxy API on a proprietary backend for security purposes. I'm looking for a way to rely on your type definitions for those APIs (e.g., Product, Prices, Customer etc) on the client and it doesn't really make sense to install the Node SDK just for that purpose (don't want server lib code ending up in my frontend bundle either). Does that make more sense?

**Comment by vijayasingam-paddle** [comment]
Hi @phil221, 

Thank you for the additional context. It now makes sense why you need types in the snake case. 

I agree, that adding our Node SDK to a client-side bundle would not be good.

This repository however is not the right place to do this as paddle.js is a subset of our resources and has limited access to our API.

Based on your implementation, It looks like an independent package with all the types in snake case format for your client-side code would be the best solution.

Can you please open a new feature request in our [Node SDK repo](https://github.com/PaddleHQ/paddle-node-sdk)? I can't promise that we will get this out soon, but I will discuss it with the rest of the team and we can build something.

Thank you.
